language: node_js
node_js:
  - 8
  - 10
  - 12

script: echo "Running against $(node -v) ..."

jobs:
  include:
    - stage: test
      script: npm run lint
      on:
        all_branches: true
    - script: npm run test
      on:
        all_branches: true
    - stage: npm release
      node_js: "12"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $SSTK_NPM_TOKEN
        email: tech.activation.team@shutterstock.com
        on:
          tags: true
