language: node_js

node_js:
  - 8
  - 10
  - 12

cache: yarn

install: yarn
script:
  - npm run test
  - npm test

jobs:
  include:
    - stage: npm release
      node_js: "12"
      deploy:
        provider: npm
        api_key: $SSTK_NPM_TOKEN
        email: tech.activation.team@shutterstock.com
        skip_cleanup: true
        on:
          tags: true
